language: python
sudo: false
arch:
  - amd64
  - arm64
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
services:
  - xvfb
install:
- wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-$(uname -m).sh -O mambaforge.sh
- bash mambaforge.sh -b -p $HOME/mambaforge
- export PATH="$HOME/mambaforge/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- mamba info -a
- mamba create -y -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas
  scipy matplotlib seaborn scikit-learn umap-learn requests
- source activate testenv
- pip install .
- cp tests/matplotlibrc .
before_script:
- [[ -d "$HOME/hypertools_data" ]] && rm -rf "$HOME/hypertools_data"
- if [ ${TRAVIS_PYTHON_VERSION} == '3.6' ]; then pip install flake8; flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics; fi
script: pytest -sv .
notifications:
  slack:
    rooms:
      secure: BhLZdh14a8WQlNUcJ6WD7AXu/TzCiryJgKiW8RMtX8eRiNKGlZo7mPJ4b+hdODtB5satKBt9d3GYrozJu19IDLDuppcwOw4zXFCbW9WwNJQHXEt6JHU2t51q41CZF75s5H7/qTkplwuhqn2NYwVQQ00KqKjrkbS0oQOiQypU+LZaUUXlITdSeKo/npUY6J0xkvnWFqIOgD8MoGyrR15U0bm7eG4IPSTeu/WJBINMmPdQcxjcJ8kmWv/WjhvdoypI+mgBeALi2HEpQ5SVRWk7HFvB0jRQZAhEutDQOjo/J0dudXCAxvBcD8uZCAF0fxiJx3TTz7Svj2tJd5jnrPJ41BTic9qT5yQiir+SkacgRgs1UFKMxznVT4jXBDP+16mVwbVxGFcNOVMWAkaeB/wVB1i5LQkh0VbWofjZuG8Fi+2geMaAWaGcWPHL9ZdGHc1MCdvW5zL/sq+NJwDDjtSKZB74i4qkL5mnoSl4Q9VArPUxVH7QxKBDkO9i51dsYNjrP8sEmb4EeyedqdGo/jVJaB5NXtlktQONhcpTKT77gDXel8KYhKLfIfemebpMqELXZEoigDUxr/37GXnf6sBIiDzQZitk6vAd8W4fYi8Xjia3px2OyrvZTwm14tQYRF0zZJWkZVEaJ/nQd4b0+B65YNcRrmNP9TQh9spYWYqLFQg=
