notifications:
  slack: context-lab:HbiEYsCVdh8R8Zpu0uqnMsoK
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - ":parrotdad: :parrotdad: :parrotdad:"
language: python
sudo: false
python:
  - "2.7"
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas scipy matplotlib seaborn scikit-learn
  - source activate testenv
  - pip install -r requirements.txt
  - python setup.py install
  - cp tests/matplotlibrc .
script: py.test
