notifications:
  slack: context-lab:HbiEYsCVdh8R8Zpu0uqnMsoK
os:
  - osx
  - linux
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -e ."
# command to run tests
script: pytest
